CREATE OR REPLACE FUNCTION CALCULATE_YIELD
(
    P_CROP_ID NUMBER
)
RETURN NUMBER
IS
    V_AREA NUMBER;
    V_PRODUCTION NUMBER;
    V_YIELD NUMBER;
BEGIN
    SELECT AREA, PRODUCTION
    INTO V_AREA, V_PRODUCTION
    FROM CROP_PRODUCTION
    WHERE CROP_ID = P_CROP_ID;

    IF V_AREA = 0 THEN
        RAISE_APPLICATION_ERROR(-20001,
        'Cultivated area cannot be zero');
    END IF;

    V_YIELD := V_PRODUCTION / V_AREA;

    RETURN V_YIELD;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20002,
        'Crop record not found');

    WHEN OTHERS THEN
        RAISE;
END;
/

Execution
SELECT CALCULATE_YIELD(1) AS YIELD
FROM DUAL;
