CREATE OR REPLACE PROCEDURE STATE_WISE_REPORT
(
    P_STATE_NAME VARCHAR2
)
IS
    V_TOTAL_PRODUCTION NUMBER;
    V_TOTAL_AREA       NUMBER;
    V_AVG_YIELD        NUMBER;
BEGIN

    SELECT SUM(PRODUCTION),
           SUM(AREA),
           AVG(YIELD)
    INTO V_TOTAL_PRODUCTION,
         V_TOTAL_AREA,
         V_AVG_YIELD
    FROM CROP_PRODUCTION
    WHERE UPPER(STATE_NAME) = UPPER(P_STATE_NAME);

    IF V_TOTAL_AREA IS NULL THEN
        RAISE_APPLICATION_ERROR(
            -20004,
            'State not found'
        );
    END IF;

    IF V_TOTAL_AREA = 0 THEN
        RAISE_APPLICATION_ERROR(
            -20005,
            'Total cultivated area is zero'
        );
    END IF;

    DBMS_OUTPUT.PUT_LINE('STATE: ' || P_STATE_NAME);
    DBMS_OUTPUT.PUT_LINE('TOTAL AREA: ' || V_TOTAL_AREA);
    DBMS_OUTPUT.PUT_LINE('TOTAL PRODUCTION: ' || V_TOTAL_PRODUCTION);
    DBMS_OUTPUT.PUT_LINE('AVERAGE YIELD: ' || ROUND(V_AVG_YIELD, 2));

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END;
/
Execution
BEGIN
    STATE_WISE_REPORT('Tamil Nadu');
END;
/
