CREATE TABLE CROP_PRODUCTION (
    CROP_ID NUMBER PRIMARY KEY,
    STATE_NAME VARCHAR2(30) NOT NULL,
    DISTRICT_NAME VARCHAR2(30) NOT NULL,
    CROP_NAME VARCHAR2(30) NOT NULL,
    CROP_YEAR NUMBER(4) CHECK (CROP_YEAR >= 2000),
    SEASON VARCHAR2(20),
    AREA NUMBER(10,2) CHECK (AREA >= 0),
    PRODUCTION NUMBER(12,2) CHECK (PRODUCTION >= 0),
    YIELD NUMBER(12,2)
);
